# action.yml
name: 'Visualize References'
description: 'Visualize references'
inputs:
  bib-path:
    description: 'Path to bib file'
    required: true
    default: 'references.bib'
  metadata-path:
    description: 'folder that contains the metadata of the papers'
    required: false
    default: 'data/metadata/'
  connections-path:
    description: 'folder that contains the connections of the papers'
    required: false
    default: 'data/connections/'
  map-path:
    description: 'folder that contains the visualizations of the papers'
    required: false
    default: 'data/visualizations'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.bib-path }}
    - ${{ inputs.metadata-path }}
    - ${{ inputs.connections-path }}
    - ${{ inputs.map-path }}
